### PR TITLE
app_status

### PR DESCRIPTION
**Pull request by vlondon**
Together with https://github.com/RishabhTayal/itc-api/pull/13 it should display app status below platform label.

### CODE REVIEW

**Comment by RishabhTayal** [comment]
@vlondon are you sure we need to have a new end point just to get the status of the app? Can the status be obtained from the app metadata?

**Comment by Eliottiosdevs** [comment]
@RishabhTayal this is already added in my pr

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
@RishabhTayal it’s this value: https://imgur.com/a/JnTnm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@eliottiosdevs is this pull request supposed to be merged?

**Comment by Eliottiosdevs** [comment]
It’s possible but I’m on it but with all metadata here is only the status so I think it’s better everything, no?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@Eliottiosdevs not sure I am following you. Does you pull request #73 contains the `app_status`?

**Comment by Eliottiosdevs** [comment]
@RishabhTayal yes it is in

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
Do you want I push to PR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
I’m nearly done

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
It’s included

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
It first looks for live version if that’s null it will show edit_version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@vlondon, According to @Eliottiosdevs this data point will be added in the `app/metadata` api in the pr https://github.com/RishabhTayal/itc-api/pull/11 and #73. Don't think we need to have a separate api to just get `app_status`.

**Comment by vlondon** [comment]
Great! Let me know if you have some area in the App I can work on.

**Comment by RishabhTayal** [comment]
@vlondon This one can be easily done: https://github.com/RishabhTayal/ReviewMonitor/issues/47. We also have a slack channel for development related discussion. Let me know if you want to join.

**Comment by RishabhTayal** [comment]
Closing this

**Pull request closed without merging**
